### ISSUE TITLE
readabilitySAX doesn't handle web pages which require cookie

### ISSUE THREAD

**Issue by cliffano** [fb55/readabilitySAX#43]
A number of web pages which require cookie to be enabled end up responding with a page containing a message "Cookie must be enabled", which then gets processed by readabilitySAX as if it's the expected content of the page.

It looks like that this happens due to the use of minreq https://github.com/fb55/readabilitySAX/blob/master/lib/getURL.js#L28 which doesn't support cookie by design in order to improve performance.

Does readabilitySAX purposely ignore web pages which require cookie for performance reason?
Or are you open to the possibility of replacing minreq with request or any other module that supports cookie?

**Comment by fb55** [comment]
I wanted to remove the `getURL` interface at some point, in favor of the `WritableStream` interface, which you could simply pipe your request response into. Nevertheless, the last commit to this repo was almost two years ago and the project definitely isn't under active development anymore. Additional features aren't a priority, especially when I haven't encountered the use case yet.

**Comment by cliffano** [comment]
Thanks for the confirmation :). I'll move to other readability module in that case.
